<?
$PERM["hronology"]["2"]="R";
$PERM["hronology"]["3"]="R";
$PERM["hronology"]["4"]="R";
$PERM["hronology"]["6"]="R";
$PERM["hronology"]["5"]="R";
$PERM["hronology"]["*"]="R";
$PERM["login"]["2"]="D";
$PERM["login"]["6"]="D";
$PERM["local"]["2"]="X";
$PERM["local"]["3"]="X";
$PERM["local"]["4"]="X";
$PERM["local"]["5"]="X";
$PERM["bitrix"]["2"]="X";
$PERM["bitrix"]["5"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>